name       : perl-datetime-format-builder
version    : '0.83'
release    : 7
source     :
    - https://cpan.metacpan.org/authors/id/D/DR/DROLSKY/DateTime-Format-Builder-0.83.tar.gz : 61ffb23d85b3ca1786b2da3289e99b57e0625fe0e49db02a6dc0cb62c689e2f2
homepage   : https://metacpan.org/pod/DateTime::Format::Builder
license    : Artistic-2.0
component  : programming.perl
summary    : DateTime::Format::Builder - Create DateTime parser classes and objects
description: |
    DateTime::Format::Builder creates DateTime parsers. Many string formats of dates and times are simple and just require a basic regular expression to extract the relevant information. Builder provides a simple way to do this without writing reams of structural code.
builddeps  :
    - perl-datetime
rundeps    :
    - perl-datetime
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
