name       : perl-datetime-format-builder
version    : 0.81
release    : 5
source     :
    - http://search.cpan.org/CPAN/authors/id/D/DR/DROLSKY/DateTime-Format-Builder-0.81.tar.gz : 7cd58a8cb53bf698407cc992f89e4d49bf3dc55baf4f3f00f1def63a0fff33ef
license    : Artistic-2.0
component  : programming.perl
summary    : Create DateTime parser classes and objects.
description: |
    Create DateTime parser classes and objects.
builddeps  :
    - perl-datetime
rundeps    :
    - perl-datetime
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
